// VR Optimization Suite — Export Menu
// Exports scan results as formatted .txt, structured .json, or self-contained .html

import React, { useState, useRef, useEffect } from 'react'
import { useScanStore } from '../../stores/scan-store'
import { useFixStore } from '../../stores/fix-store'
import { generateHtmlReport } from '../../utils/generate-html-report'
import type { NetworkAdapter } from '../../../main/scanner/types'
import type { Finding } from '../../../main/rules/types'

// ── Text Formatter ────────────────────────────────────────────

function formatTextReport(findings: Finding[], scanData: any): string {
  const lines: string[] = []
  const now = new Date().toLocaleString()
  const scanTime = scanData ? new Date(scanData.timestamp).toLocaleString() : now

  lines.push('═══════════════════════════════════════════════════════════')
  lines.push('  VRYIONICS VR OPTIMIZATION SUITE — SCAN REPORT')
  lines.push('═══════════════════════════════════════════════════════════')
  lines.push(`  Scan Time : ${scanTime}`)
  lines.push(`  Export    : ${now}`)
  if (scanData?.scanDurationMs) {
    lines.push(`  Duration  : ${(scanData.scanDurationMs / 1000).toFixed(1)}s`)
  }
  lines.push('')

  // System summary
  if (scanData) {
    lines.push('SYSTEM SUMMARY')
    lines.push('─────────────────────────────────────────────────────────')
    if (scanData.cpu) {
      const c = scanData.cpu
      lines.push(`  CPU    : ${c.model} (${c.cores}C/${c.threads}T @ ${c.baseClock} MHz${c.boostClock > 0 ? `, boost ${c.boostClock} MHz` : ''})`)
      lines.push(`         : ${c.avgUsage.toFixed(0)}% avg usage${c.temperature != null ? `, ${c.temperature}°C` : ''}`)
    }
    if (scanData.gpu?.devices) {
      for (const g of scanData.gpu.devices) {
        lines.push(`  GPU    : ${g.name} — ${g.vramTotal} MB VRAM`)
        lines.push(`         : ${g.utilization.toFixed(0)}% util${g.temperature > 0 ? `, ${g.temperature}°C` : ''}${g.powerDraw > 0 ? `, ${g.powerDraw.toFixed(0)} W` : ''}`)
        lines.push(`         : Driver ${g.driverVersion || 'Unknown'} | HAGS: ${g.hagsEnabled ? 'On' : 'Off'} | ReBAR: ${g.rebarEnabled ? 'On' : 'Off'}`)
      }
    }
    if (scanData.ram) {
      const r = scanData.ram
      lines.push(`  RAM    : ${r.totalGB.toFixed(1)} GB ${r.type} @ ${r.speed} MHz${r.xmpSpeed ? ` (XMP: ${r.xmpSpeed} MHz)` : ''} — ${r.channels}ch`)
      lines.push(`         : ${r.usedGB.toFixed(1)} GB used (${r.usagePercent.toFixed(0)}%)`)
    }
    if (scanData.storage?.drives) {
      for (const d of scanData.storage.drives) {
        lines.push(`  Drive  : ${d.letter}: ${d.type} — ${d.freeGB.toFixed(1)} GB free / ${d.totalGB.toFixed(1)} GB`)
      }
    }
    if (scanData.network) {
      const n = scanData.network
      if (n.wifi) {
        lines.push(`  Wi-Fi  : ${n.wifi.ssid ?? 'Connected'} | ${n.wifi.band ?? '?'} Ch${n.wifi.channel ?? '?'} | ${n.wifi.signalStrength ?? '?'}% | ${n.wifi.linkSpeed ?? '?'} Mbps`)
      }
      const eth = n.adapters.filter((a: NetworkAdapter) => a.type === 'Ethernet' && a.connected)
      for (const a of eth) {
        lines.push(`  LAN    : ${a.name} @ ${a.speed} Mbps`)
      }
      if (n.latency.gateway != null) lines.push(`  GW Lat : ${n.latency.gateway} ms`)
    }
    if (scanData.osConfig) {
      const o = scanData.osConfig
      lines.push(`  OS     : Windows ${o.windowsVersion} (Build ${o.windowsBuild})`)
      lines.push(`         : ${o.powerPlan} | Game Mode: ${o.gameModeEnabled ? 'On' : 'Off'}`)
    }
    if (scanData.vrRuntime) {
      const v = scanData.vrRuntime
      lines.push(`  VR RT  : ${v.activeRuntime ?? 'None'} | SS: ${v.supersampling != null ? (v.supersampling * 100).toFixed(0) + '%' : 'Auto'}`)
    }
    lines.push('')
  }

  // Group findings by severity
  const critical = findings.filter(f => f.result.severity === 'critical')
  const warnings = findings.filter(f => f.result.severity === 'warning')
  const info = findings.filter(f => f.result.severity === 'info')

  const printGroup = (label: string, items: Finding[], prefix: string) => {
    if (items.length === 0) return
    lines.push(`${label} (${items.length})`)
    lines.push('─────────────────────────────────────────────────────────')
    for (const f of items) {
      lines.push(`  ${prefix} [${f.result.category.toUpperCase()}] ${f.result.explanation.simple}`)
      if (f.fixAvailable) lines.push('       → Fix available in app')
      lines.push('')
    }
  }

  printGroup('CRITICAL ISSUES', critical, '🔴')
  printGroup('WARNINGS', warnings, '🟡')
  printGroup('INFORMATIONAL', info, 'ℹ️')

  if (critical.length === 0 && warnings.length === 0) {
    lines.push('✅ No critical issues or warnings detected.')
    lines.push('')
  }

  lines.push('═══════════════════════════════════════════════════════════')
  lines.push('  Generated by Vryionics VR Optimization Suite')
  lines.push('═══════════════════════════════════════════════════════════')

  return lines.join('\n')
}

// ── Download Helper ───────────────────────────────────────────

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

// ── Component ─────────────────────────────────────────────────

export function ExportMenu(): React.ReactElement {
  const [open, setOpen] = useState(false)
  const [exporting, setExporting] = useState(false)
  const ref = useRef<HTMLDivElement>(null)
  const { findings, lastScanData, actionPlan } = useScanStore()
  const { fixHistory } = useFixStore()

  // Close on outside click
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false)
    }
    if (open) document.addEventListener('mousedown', handler)
    return () => document.removeEventListener('mousedown', handler)
  }, [open])

  const stamp = lastScanData
    ? new Date(lastScanData.timestamp).toISOString().slice(0, 10)
    : new Date().toISOString().slice(0, 10)

  const exportTxt = async () => {
    setExporting(true)
    setOpen(false)
    try {
      const text = formatTextReport(findings, lastScanData)
      downloadFile(text, `vr-scan-${stamp}.txt`, 'text/plain')
    } finally {
      setExporting(false)
    }
  }

  const exportJson = async () => {
    setExporting(true)
    setOpen(false)
    try {
      const payload = {
        exportedAt: new Date().toISOString(),
        appVersion: '0.1.0',
        scanData: lastScanData,
        findings: findings.map(f => ({
          id: f.id,
          ruleId: f.result.ruleId,
          category: f.result.category,
          severity: f.result.severity,
          simple: f.result.explanation.simple,
          advanced: f.result.explanation.advanced,
          fixAvailable: f.fixAvailable,
          fixed: f.fixed
        }))
      }
      downloadFile(JSON.stringify(payload, null, 2), `vr-scan-${stamp}.json`, 'application/json')
    } finally {
      setExporting(false)
    }
  }

  const exportHtml = async (redact = false) => {
    setExporting(true)
    setOpen(false)
    try {
      const html = generateHtmlReport({
        scanData: lastScanData,
        findings,
        actionPlan,
        fixHistory,
        redact,
      })
      const suffix = redact ? '-redacted' : ''
      downloadFile(html, `vr-scan-${stamp}${suffix}.html`, 'text/html')
    } finally {
      setExporting(false)
    }
  }

  const hasData = findings.length > 0 || !!lastScanData

  return (
    <div className="relative" ref={ref}>
      <button
        className="glass-panel-sm border border-white/8 btn-spring px-3 py-2 text-xs text-gray-300 hover:text-white hover:border-white/20 transition-all flex items-center gap-2"
        onClick={() => setOpen((o) => !o)}
        disabled={!hasData || exporting}
        title={!hasData ? 'Run a scan first' : 'Export report'}
      >
        <svg width="13" height="13" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
          <path d="M8 2v8M5 7l3 3 3-3M2 12v1a1 1 0 001 1h10a1 1 0 001-1v-1" />
        </svg>
        {exporting ? 'Exporting…' : 'Export'}
      </button>

      {open && (
        <div className="absolute right-0 top-full mt-1 glass-panel border border-white/10 rounded-lg overflow-hidden z-30 w-44 shadow-xl modal-animate">
          <button
            className="w-full flex items-center gap-3 px-4 py-3 text-xs text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
            onClick={exportTxt}
          >
            <span className="text-base">📄</span>
            <div className="text-left">
              <p className="font-medium">Text Report</p>
              <p className="text-[10px] text-gray-500">.txt — human readable</p>
            </div>
          </button>
          <div className="border-t border-white/5" />
          <button
            className="w-full flex items-center gap-3 px-4 py-3 text-xs text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
            onClick={exportJson}
          >
            <span className="text-base">📊</span>
            <div className="text-left">
              <p className="font-medium">JSON Data</p>
              <p className="text-[10px] text-gray-500">.json — full scan data</p>
            </div>
          </button>
          <div className="border-t border-white/5" />
          <button
            className="w-full flex items-center gap-3 px-4 py-3 text-xs text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
            onClick={() => exportHtml(false)}
          >
            <span className="text-base">🌐</span>
            <div className="text-left">
              <p className="font-medium">HTML Report</p>
              <p className="text-[10px] text-gray-500">.html — shareable, self-contained</p>
            </div>
          </button>
          <button
            className="w-full flex items-center gap-3 px-4 py-3 text-xs text-gray-300 hover:bg-white/5 hover:text-white transition-colors"
            onClick={() => exportHtml(true)}
          >
            <span className="text-base">🛡</span>
            <div className="text-left">
              <p className="font-medium">HTML Report (Redacted)</p>
              <p className="text-[10px] text-gray-500">For forum / community sharing — strips Wi-Fi SSID, user paths, MACs, emails</p>
            </div>
          </button>
        </div>
      )}
    </div>
  )
}
